version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  webserver:
    build: .
    container_name: webserver
    restart: always
    env_file:
      - .env
      - .env.local
    depends_on:
      - mysql
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html

volumes:
  mysql-data:
